### ISSUE TITLE
Bug yml

### ISSUE THREAD

**Issue by mikesaurio** [citydevs/infracciones#2]
por alguna razon el gitignore no ignora los yml :(

**Comment by juanjcsr** [comment]
Si los ignora pero ya fueron agregados antes entonces no los quita, enseguida los arreglo :)

**Comment by juanjcsr** [comment]
Que acabo de revisar y técnicamente no debería haber problema ya que el Database.yml no expone usuarios ni nada :+1: Voy a subir un database.yml de ejemplo nomas :dancer:

**Comment by juanjcsr** [comment]
@mikesaurio si quieres borrar los yml locales (que no lo recomiendo porque te quedarías sin base de datos o aplicación) puedes hacer esto:

```
git rm -rf --cached . 
git add .
git commit -m "archivos del gitignore borrados"
```

En este momento en el repo ya no hay :smile:
